# superuser permission is required to have this build
sudo: required

language: generic
services:
  # Telling  we need docker to build
  - docker  


# steps needed to do before test and deploy happens
before_install:
  # pujabapat/docker-react - docker username and the github repo name
  - docker build -t pujabapat/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pujabapat/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-439828442360"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
